### ISSUE TITLE
After I have implemented the Transitions plugins theres now bugs?

### ISSUE THREAD

**Issue by ghost** [Nemesis-AS/godot-transitions#1]
hey, I implemented the transition plugin and now i am encountering errors that wouldn't happen without the transition plugin, do you have any idea about this? I followed a HeartBeast 1-bit godot course so I have the script Utils, but 
*Attempt to call function 'add_child' in base 'null instance' on a null instance.* happens

https://user-images.githubusercontent.com/74095141/115126924-0182b500-a016-11eb-8632-71b84f44f6ec.mp4

https://user-images.githubusercontent.com/74095141/115126925-047da580-a016-11eb-88b3-be7f571ecb64.mp4

**Comment by Nemesis-AS** [comment]
Sorry for responding late, but the big has been fixed with the latest commit
